export const DISPLAY_LOADER = 'DISPLAY_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'

export const FETCH_CHARACTERS = 'FETCH_CHARACTERS'
export const GET_CHARACTERS = 'GET_CHARACTERS'

export const NEXT_PAGE = 'NEXT_PAGE'

export const REPORT_ERROR = 'REPORT_ERROR'

export const DISPLAY_BACKDROP = 'DISPLAY_BACKDROP'
export const HIDE_BACKDROP = 'HIDE_BACKDROP'